name: 'Bug report'
title: '[BUG] - YOUR_ISSUE_TITLE_HERE_REPLACE_ME'
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue :pray:.
        The more information you fill in, the better the community can help you.
  - type: input
    id: version
    attributes:
      label: mui-builder Version
      description: |
        Please provide the version of mui-builder you are using.
        You can find the version number in the package.json file.
      placeholder: ex. 0.0.6
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the challenge you are running into.
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Your Example Website or App
      description: |
        Which website or app were you using when the bug happened?

      placeholder: |
        e.g. c/edit/...... OR Github Repo
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce the Bug or Issue
      description: Describe the steps we have to take to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Provide a clear and concise description of what you expected to happen.
      placeholder: |
        As a user, I expected ___ behavior but i am seeing ___
    validations:

  - type: textarea
    id: screenshots_or_videos
    attributes:
      label: Screenshots or Videos
      description: |
        If applicable, add screenshots or a video to help explain your problem.
        For more information on the supported file image/file types and the file size limits, please refer
        to the following link: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files
      placeholder: |
        You can drag your video or image files inside of this editor ↓
  - type: input
    id: os
    attributes:
      label: Operating System Version
      description: What operating system are you using?
      placeholder: |
        - OS: [e.g. macOS, Windows, Linux]
    validations:
  - type: dropdown
    id: browser_type
    attributes:
      label: Browser
      description: Select the browsers where the issue can be reproduced (that you know of).
      options:
        - 'Chrome'
        - 'Firefox'
        - 'Safari'
        - 'Edge'
        - 'Opera'
        - 'Other (add additonal context)'
    validations:
