name: Feature request
<<<<<<< HEAD
title: '[Feat] YOUR_FEATURE_TITLE_HERE_REPLACE_ME'
labels: [feature request]
description: |
  💡 Suggest an idea for the `mui-builder` project
=======
title: '[Feature Request] YOUR_FEATURE_TITLE_HERE_REPLACE_ME'
labels: [feature request]
description: |
  💡 Suggest an idea for the `NextUI` project
>>>>>>> 64f89a26b25eae6085d73f17170e125dce20c79e
  Examples
    - propose a new component
    - improve an exiting component
    - ....etc
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for requesting features only! For example, requesting a new component, behavior ... etc
        If you want to report a bug, please use the [bug report form](https://github.com/mrbadri/mui-builder/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=%5BBUG%5D+-+YOUR_ISSUE_TITLE_HERE_REPLACE_ME).
  - type: textarea
    validations:
      required: true
    attributes:
      label: PLease describe feature requested.
